### ISSUE TITLE
failHandler called when returning from background

### ISSUE THREAD

**Issue by weakfl** [grandcentrix/GCXMulticastDNSKit#10]
The failHandler gets called after successful discovery when returning from background.
I could only reproduce this on a physical device:
- start app
- start discovery
- put app into background
- return app to foreground
- failHandler gets called with the following message in the console: `dnssd_clientstub read_all(9) DEFUNCT`

**Comment by snod** [comment]
Thank you, I will have a look at it

**Comment by PaulEhrhardt** [comment]
@weakfl Thanks for reporting we stumbled upon this as well.  And unfortunately it seems like we can not fix that. 
The cause of the message is not the lib. The error message is written to syslog by Apple's mDNSResponder library which is also known as Bonjour.
The class dnssd_clientstub.c prints this error when the socket no longer existing or functioning (a.k.a. defunct), the mDNS deamon crashes or a general error on OS level occours.
See also line 213 in dnssd_clientstub.c: 
https://opensource.apple.com/source/mDNSResponder/mDNSResponder-878.1.1/mDNSShared/dnssd_clientstub.c.auto.html

Suggested workaround: skip error and restart discovery when returning from background

**Comment by weakfl** [comment]
Thanks for looking into it @PaulEhrhardt. I've already implemented a workaround, so I'll just leave that in place if the problem is at os level.

Thanks for development of this nice framework btw!
