### ISSUE TITLE
Incorrect use of objc_storeWeak() and objc_loadWeak()

### ISSUE THREAD

**Issue by weakfl** [grandcentrix/GCXMulticastDNSKit#11]
It seems you're affected by this bug:
http://www.openradar.me/28943305

Clearing the `NetServiceBrowserDelegate` in deinit seems to work around this issue:
```swift
    deinit {
        let _ = items?.map {
            $0.netServiceBrowser.delegate = nil
        }
    }
```

**Comment by PaulEhrhardt** [comment]
Thanks for pointing us to the rdar. I saw this several times as well and I will look onto this asap.

**Comment by weakfl** [comment]
You're welcome. My suggested workaround is basically what the Chromium devs [have done](https://codereview.chromium.org/2445343005/).
