### ISSUE TITLE
DiscoveryDelegate possible strong reference cycle

### ISSUE THREAD

**Issue by weakfl** [grandcentrix/GCXMulticastDNSKit#12]
Looks like the `DiscoveryDelegate` protocol should be a class type protocol and the delegate variable should be weak to avoid a strong reference cycle?

```
public protocol DiscoveryDelegate: class
```

```swift
public weak var delegate: DiscoveryDelegate?
```

**Comment by PaulEhrhardt** [comment]
Yep we're  checking if there is the need to change it to class type protocol.
