### ISSUE TITLE
Readme corrections

### ISSUE THREAD

**Issue by weakfl** [grandcentrix/GCXMulticastDNSKit#13]
Tag in Cocoapod installation instructions should be **v**1.2.0 instead of 1.2.0:
```
pod 'GCXMulticastDNSKit', :git => 'https://github.com/grandcentrix/GCXMulticastDNSKit.git', :tag => 'v1.2.0'
```

Method signature is wrong (with~~Configurations~~):
```swift
discovery = Discovery(with: configurations, delegate: self)
```

**Comment by PaulEhrhardt** [comment]
Valid point @weakfl. We will overhaul the readme accordingly.
