### ISSUE TITLE
Discovery not working with esp 32 module

### ISSUE THREAD

**Issue by RajeevUdayan** [grandcentrix/GCXMulticastDNSKit#21]
Is this support esp 32 wifi module? I tried with different modules but **discoveryDidDiscover(service: DiscoveryService)** is not triggered when connected to a **esp 32**.

**Comment by PaulEhrhardt** [comment]
The ESP 32 conforms to IEEE 802.11 standard supporting all b/g/n networks which i assume to work without issues. But on the other hand we have no test history with this particular WiFi module available.

We are using this library in a customer app with more than monthly 60k users worldwide (using various WiFi modules) without any reported problems for the last two years.

**Comment by PaulEhrhardt** [comment]
Please reopen with more evidence if issues re-occour.
