### ISSUE TITLE
More instructions

### ISSUE THREAD

**Issue by shubhank008** [grandcentrix/GCXMulticastDNSKit#6]
Please provide more instructions on how to use this... like a bit more better/detailed example or delegates to be used.  
I am not a iOS expert so maybe I am not able to understand well, want to try this to see if I can find my mDNS router/gateway

**Comment by PaulEhrhardt** [comment]
What kind of information do you need exactly?

**Comment by PaulEhrhardt** [comment]
We improved our readme and hope it is fine now. Feel free to approach us with further questions.
